name: cash_withdraw
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
#  nfc_manager: ^3.3.0
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.2.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  flutter_screenutil: ^5.9.0
  simple_ripple_animation: ^0.0.9
  flutter_svg: ^2.0.10+1
  flutter_nfc_kit: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  assets:
    - lib/assets/
    - lib/
  uses-material-design: true